import { Product, Collection } from './types';

export const collections: Collection[] = [
  {
    id: '1',
    name: 'Living Room',
    description: 'Sofas, chairs, and coffee tables for the heart of your home',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    productCount: 48,
    slug: 'living-room',
  },
  {
    id: '2',
    name: 'Bedroom',
    description: 'Beds, nightstands, and dressers for restful retreats',
    imageUrl: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80',
    productCount: 36,
    slug: 'bedroom',
  },
  {
    id: '3',
    name: 'Dining',
    description: 'Tables, chairs, and sideboards for memorable meals',
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80',
    productCount: 29,
    slug: 'dining',
  },
  {
    id: '4',
    name: 'Home Office',
    description: 'Desks, chairs, and storage for productive spaces',
    imageUrl: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=80',
    productCount: 24,
    slug: 'office',
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Aria Modular Sofa',
    description: 'A beautifully crafted modular sofa with clean lines and exceptional comfort. Features high-density foam cushions and premium linen upholstery.',
    price: 2499,
    originalPrice: 2999,
    category: 'Living Room',
    subcategory: 'Sofas',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
      'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=800&q=80',
    ],
    colors: ['Oatmeal', 'Charcoal', 'Sage'],
    dimensions: { width: 280, height: 85, depth: 100 },
    materials: ['Linen', 'Solid Oak'],
    inStock: true,
    rating: 4.8,
    reviewCount: 127,
    vendor: 'Nordic Living',
    tags: ['bestseller', 'sustainable'],
  },
  {
    id: '2',
    name: 'Luna Accent Chair',
    description: 'An elegant accent chair with curved silhouette and brass-finished legs. Perfect for adding a touch of sophistication to any room.',
    price: 899,
    category: 'Living Room',
    subcategory: 'Chairs',
    images: [
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80',
    ],
    colors: ['Terracotta', 'Forest Green', 'Navy'],
    dimensions: { width: 75, height: 82, depth: 80 },
    materials: ['Velvet', 'Brass'],
    inStock: true,
    rating: 4.9,
    reviewCount: 89,
    vendor: 'Artisan Home',
    tags: ['new'],
  },
  {
    id: '3',
    name: 'Halo Round Coffee Table',
    description: 'A stunning round coffee table featuring a marble top and sculptural oak base. The perfect centerpiece for your living space.',
    price: 1299,
    category: 'Living Room',
    subcategory: 'Tables',
    images: [
      'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=800&q=80',
    ],
    colors: ['White Marble', 'Black Marble'],
    dimensions: { width: 100, height: 40, depth: 100 },
    materials: ['Marble', 'Oak'],
    inStock: true,
    rating: 4.7,
    reviewCount: 56,
    vendor: 'Stone & Wood Co.',
    tags: ['bestseller'],
  },
  {
    id: '4',
    name: 'Haven Platform Bed',
    description: 'A minimalist platform bed with integrated headboard and hidden storage. Crafted from sustainable solid oak.',
    price: 1899,
    originalPrice: 2199,
    category: 'Bedroom',
    subcategory: 'Beds',
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80',
    ],
    colors: ['Natural Oak', 'Walnut', 'White Oak'],
    dimensions: { width: 160, height: 95, depth: 210 },
    materials: ['Solid Oak'],
    inStock: true,
    rating: 4.9,
    reviewCount: 203,
    vendor: 'Nordic Living',
    tags: ['sustainable', 'bestseller'],
  },
  {
    id: '5',
    name: 'Serenity Nightstand',
    description: 'A sleek nightstand with soft-close drawer and open shelf. Features elegant brass hardware.',
    price: 449,
    category: 'Bedroom',
    subcategory: 'Nightstands',
    images: [
      'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=800&q=80',
    ],
    colors: ['Natural Oak', 'Walnut'],
    dimensions: { width: 50, height: 55, depth: 40 },
    materials: ['Oak', 'Brass'],
    inStock: true,
    rating: 4.6,
    reviewCount: 78,
    vendor: 'Artisan Home',
    tags: [],
  },
  {
    id: '6',
    name: 'Grace Dining Table',
    description: 'An elegant oval dining table with tapered legs and beautiful wood grain. Seats 6-8 comfortably.',
    price: 1799,
    category: 'Dining',
    subcategory: 'Tables',
    images: [
      'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80',
    ],
    colors: ['Natural Oak', 'Dark Walnut'],
    dimensions: { width: 200, height: 75, depth: 100 },
    materials: ['Solid Oak'],
    inStock: true,
    rating: 4.8,
    reviewCount: 94,
    vendor: 'Nordic Living',
    tags: ['new'],
  },
  {
    id: '7',
    name: 'Curve Dining Chair',
    description: 'A sculptural dining chair with organic curves and exceptional comfort. Stackable design.',
    price: 349,
    category: 'Dining',
    subcategory: 'Chairs',
    images: [
      'https://images.unsplash.com/photo-1503602642458-232111445657?w=800&q=80',
    ],
    colors: ['Cream', 'Black', 'Terracotta'],
    dimensions: { width: 52, height: 80, depth: 55 },
    materials: ['Molded Plywood', 'Wool Blend'],
    inStock: true,
    rating: 4.7,
    reviewCount: 156,
    vendor: 'Modern Craft',
    tags: ['bestseller'],
  },
  {
    id: '8',
    name: 'Focus Desk',
    description: 'A minimalist desk with integrated cable management and hidden drawer. Perfect for focused work.',
    price: 999,
    category: 'Home Office',
    subcategory: 'Desks',
    images: [
      'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
    ],
    colors: ['White/Oak', 'Black/Walnut'],
    dimensions: { width: 140, height: 75, depth: 70 },
    materials: ['Oak', 'Powder-Coated Steel'],
    inStock: true,
    rating: 4.8,
    reviewCount: 112,
    vendor: 'Work Studio',
    tags: ['bestseller'],
  },
  {
    id: '9',
    name: 'Ergo Task Chair',
    description: 'An ergonomic task chair with adjustable lumbar support, armrests, and breathable mesh back.',
    price: 749,
    originalPrice: 849,
    category: 'Home Office',
    subcategory: 'Chairs',
    images: [
      'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800&q=80',
    ],
    colors: ['Black', 'Gray'],
    dimensions: { width: 68, height: 120, depth: 68 },
    materials: ['Mesh', 'Aluminum'],
    inStock: true,
    rating: 4.9,
    reviewCount: 287,
    vendor: 'Work Studio',
    tags: ['bestseller', 'ergonomic'],
  },
  {
    id: '10',
    name: 'Arc Floor Lamp',
    description: 'A sculptural arc floor lamp with adjustable arm and warm diffused lighting. Makes a statement in any room.',
    price: 599,
    category: 'Living Room',
    subcategory: 'Lighting',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
    ],
    colors: ['Brass', 'Matte Black'],
    dimensions: { width: 40, height: 180, depth: 120 },
    materials: ['Brass', 'Linen'],
    inStock: true,
    rating: 4.6,
    reviewCount: 67,
    vendor: 'Lumière',
    tags: ['new'],
  },
  {
    id: '11',
    name: 'Woven Storage Basket Set',
    description: 'Hand-woven storage baskets in three sizes. Made from sustainable seagrass with leather handles.',
    price: 149,
    category: 'Living Room',
    subcategory: 'Storage',
    images: [
      'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800&q=80',
    ],
    colors: ['Natural'],
    materials: ['Seagrass', 'Leather'],
    inStock: true,
    rating: 4.5,
    reviewCount: 43,
    vendor: 'Artisan Home',
    tags: ['sustainable'],
  },
  {
    id: '12',
    name: 'Cloud Sectional',
    description: 'An ultra-comfortable modular sectional with deep seats and plush down-filled cushions. Pure relaxation.',
    price: 4299,
    category: 'Living Room',
    subcategory: 'Sofas',
    images: [
      'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80',
    ],
    colors: ['Cream', 'Stone', 'Charcoal'],
    dimensions: { width: 320, height: 80, depth: 180 },
    materials: ['Performance Fabric', 'Down Fill'],
    inStock: true,
    rating: 4.9,
    reviewCount: 189,
    vendor: 'Nordic Living',
    tags: ['bestseller', 'luxury'],
  },
];

export const getProductsByCategory = (category: string): Product[] => {
  return products.filter(p => p.category.toLowerCase() === category.toLowerCase());
};

export const getProductById = (id: string): Product | undefined => {
  return products.find(p => p.id === id);
};

export const getFeaturedProducts = (): Product[] => {
  return products.filter(p => p.tags?.includes('bestseller')).slice(0, 4);
};

export const getNewProducts = (): Product[] => {
  return products.filter(p => p.tags?.includes('new'));
};
